name: Strip

on:
  push:
    branches:
      - main

jobs:
  strip:
    name: Strip
    runs-on: windows-latest
    env:
      tag: "v0.1.0"

    steps:
      - name: Strip variable
        shell: pwsh
        run: |
          $tag = $env:tag
          $version = $tag -replace '^v', ''
          echo "version=$version" >> $env:GITHUB_ENV

      - name: Print tag
        run: echo ${{ env.version }}
